changelog:
  exclude:
    labels:
      - exclude from release

  categories:
    - title: ":bangbang: Breaking Changes"
      labels:
        - breaking change
        - breaking

    - title: ":heart: Features"
      labels:
        - feature
        - feat

    - title: ":bug: Bug Fixes"
      labels:
        - bug fix
        - fix

    - title: Other Changes
      labels:
        - change
