env:
  browser: true
  es6: true
  node: true
  jest: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersio: 2018
  sourceType: module
  project: tsconfig.json

plugins:
  - "@typescript-eslint"

rules:
  indent:
    - error
    - 2

  linebreak-style:
    - error
    - windows

  quotes:
    - error
    - single

  comma-dangle:
    - error
    - always-multiline

  object-shorthand: error
  no-useless-rename: error

  no-multiple-empty-lines:
    - error
    - max: 1
      maxBOF: 0
      maxEOF: 0

  semi: 0
  "@typescript-eslint/semi":
    - error
    - always
