version: 2.1

orbs:
  codecov: codecov/codecov@4.1.0

executors:
  executor_node_18:
    docker:
      - image: cimg/node:18.20.4
    working_directory: ~/map-number

  executor_node_20:
    docker:
      - image: cimg/node:20.17.0
    working_directory: ~/map-number

  executor_node_21:
    docker:
      - image: cimg/node:21.7.3
    working_directory: ~/map-number

  executor_node_22:
    docker:
      - image: cimg/node:22.7.0
    working_directory: ~/map-number

commands:
  command_checkout_cache_install:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-map-number-{{ checksum "package-lock.json" }}
            - v2-deps-map-number-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v2-deps-map-number-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  command_lint:
    steps:
      - run:
          name: Lint Code
          command: npm run lint

  command_test_and_build:
    steps:
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build
          command: npm run build

  command_save_workspace:
    steps:
      - persist_to_workspace:
          root: ~/map-number
          paths:
            - .

  command_restore_workspace:
    steps:
      - attach_workspace:
          at: ~/map-number

  command_publish_to_npm:
    steps:
      - run:
          name: Login to npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish to npm
          command: npm publish

jobs:
  job_lint:
    description: Lint Code
    executor: executor_node_20
    steps:
      - command_checkout_cache_install
      - command_lint
      - command_save_workspace

  job_node_18_test_and_build:
    description: Test and Build on NodeJS 18
    executor: executor_node_18
    steps:
      - command_checkout_cache_install
      - command_test_and_build

  job_node_20_test_and_build:
    description: Test and Build on NodeJS 20
    executor: executor_node_20
    steps:
      - command_restore_workspace
      - command_test_and_build
      - command_save_workspace

  job_node_21_test_and_build:
    description: Test and Build on NodeJS 21
    executor: executor_node_21
    steps:
      - command_checkout_cache_install
      - command_test_and_build

  job_node_22_test_and_build:
    description: Test and Build on NodeJS 22
    executor: executor_node_22
    steps:
      - command_checkout_cache_install
      - command_test_and_build

  job_upload_coverage:
    description: Upload coverage to Codecov
    executor: executor_node_20
    steps:
      - command_restore_workspace
      - codecov/upload:
          file: coverage/*.json

  job_publish_to_npm:
    description: Publish package to npm
    executor: executor_node_20
    steps:
      - command_restore_workspace
      - command_publish_to_npm

workflows:
  workflow_ci:
    jobs:
      - job_lint:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - job_node_18_test_and_build:
          requires:
            - job_lint
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - job_node_20_test_and_build:
          requires:
            - job_lint
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - job_node_21_test_and_build:
          requires:
            - job_lint
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - job_node_22_test_and_build:
          requires:
            - job_lint
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - job_upload_coverage:
          requires:
            - job_node_18_test_and_build
            - job_node_20_test_and_build
            - job_node_21_test_and_build
            - job_node_22_test_and_build
          filters:
            branches:
              only: /main/

      - job_publish_to_npm:
          context: npm
          requires:
            - job_node_18_test_and_build
            - job_node_20_test_and_build
            - job_node_21_test_and_build
            - job_node_22_test_and_build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
