version: 2.1

orbs:
  codecov: codecov/codecov@4.1.0

executors:
  executor_node_16:
    docker:
      - image: cimg/node:16.20
    working_directory: ~/map-number

  executor_node_18:
    docker:
      - image: cimg/node:18.20
    working_directory: ~/map-number

  executor_node_20:
    docker:
      - image: cimg/node:20.15
    working_directory: ~/map-number

commands:
  command_checkout_cache_install:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-map-number-{{ checksum "package-lock.json" }}
            - v2-deps-map-number-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v2-deps-map-number-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  command_test_and_build:
    steps:
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build
          command: npm run build

  command_save_workspace:
    steps:
      - persist_to_workspace:
          root: ~/map-number
          paths:
            - .

  command_restore_workspace:
    steps:
      - attach_workspace:
          at: ~/map-number

  command_publish_to_npm:
    steps:
      - run:
          name: Login to npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish to npm
          command: npm publish

  command_ci:
    steps:
      - command_checkout_cache_install
      - command_test_and_build

jobs:
  job_test_and_build_node_16:
    executor: executor_node_16
    steps:
      - command_ci
      - command_save_workspace

  job_test_and_build_node_18:
    executor: executor_node_18
    steps:
      - command_ci

  job_test_and_build_node_20:
    executor: executor_node_20
    steps:
      - command_ci

  job_upload_coverage:
    executor: executor_node_16
    steps:
      - command_restore_workspace
      - codecov/upload:
          file: coverage/*.json

  job_publish_to_npm:
    executor: executor_node_16
    steps:
      - command_restore_workspace
      - command_publish_to_npm

workflows:
  workflow_ci:
    jobs:
      - job_test_and_build_node_16:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - job_test_and_build_node_18:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - job_test_and_build_node_20:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - job_upload_coverage:
          requires:
            - job_test_and_build_node_16
            - job_test_and_build_node_18
            - job_test_and_build_node_20
          filters:
            branches:
              only: /master/

      - job_publish_to_npm:
          context: npm
          requires:
            - job_test_and_build_node_16
            - job_test_and_build_node_18
            - job_test_and_build_node_20
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
