export { default as map } from './map'
export { default as floor } from './floor'
export { default as ceil } from './ceil'
export { default as round } from './round'
export { default as limit, default as clamp } from './limit'
export { default as compile, default as create, default as wrap } from './compile'
export { MapNumberFunction, CompiledMapNumberFunction } from './types'
